; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 18 2017 23:51:32 GMT-0700 (Pacific Daylight Time)


G90

; Move quickly to X axis endstop and stop there (first pass)
G1 X-130 F1800 S1

