; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 18 2017 23:51:32 GMT-0700 (Pacific Daylight Time)

G90
G1 X132.2 F12000
M400
M106 P1 S0
M106 P0 S255
