; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 18 2017 23:51:32 GMT-0700 (Pacific Daylight Time)

; Wait for set temperatures to be reached
M116 P1
